name: Docker Build & Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} .

      - name: Push da imagem
        run: docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
