name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    uses: ./.github/workflows/unit-test-job.yaml

  build-and-push-docker:
    needs: run-tests
    uses: ./.github/workflows/docker-build-push-job.yaml
    with:
      image_name: soatproject/fastfood-soat-app-totem
      image_tag: latest
    secrets:
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  notify-discord-build-status:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Build Status to Discord
        run: |
          # Obtenha o status do job de build
          BUILD_STATUS="${{ needs.build-and-push-docker.result }}"
          
          # Obtenha o URL do workflow run
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          MESSAGE=""
          COLOR=0
          
          if [ "$BUILD_STATUS" == "success" ]; then
            MESSAGE="✅ Docker build and push succeeded on the 'main' branch! [View Workflow](${WORKFLOW_URL})"
            COLOR=3066993
          elif [ "$BUILD_STATUS" == "failure" ]; then
            MESSAGE="❌ Docker build and push failed on the 'main' branch! [View Workflow](${WORKFLOW_URL})"
            COLOR=15158332
          else
            MESSAGE="⚠️ Docker build and push status: ${BUILD_STATUS} on the 'main' branch. [View Workflow](${WORKFLOW_URL})"
            COLOR=16776960
          fi
          
          curl -H "Content-Type: application/json" \
          -d "{\"embeds\":[{\"description\":\"$MESSAGE\",\"color\":$COLOR}]}" \
          "${{ secrets.DISCORD_WEBHOOK }}"