name: Notificar abertura de Pull Request no Discord

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  notificar_discord_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          # Obtenha os detalhes do Pull Request
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          
          # Formate a mensagem com informações do PR
          MENSAGEM="Novo Pull Request #${PR_NUMBER} aberto por ${PR_AUTHOR}:\n> **${PR_TITLE}**\n\n[Ver PR](${PR_URL})"
          
          # Envie a mensagem para o Discord usando curl
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"$MENSAGEM\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"