name: Notify Pull Requests on Discord

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:

  test-unit:
    uses: ./.github/workflows/job-unit-test.yaml@main

  test-integration:
    needs: test-unit
    uses: ./.github/workflows/job-integration-test.yaml@main
