name: Pull Request Workflow

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:

  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/job-gradle-test.yaml
    with:
      test_command: ./gradlew test --no-daemon

  integration-tests:
    name: Run Integration Tests
    needs: unit-tests
    uses: ./.github/workflows/job-gradle-test.yaml
    with:
      test_command: ./gradlew testIntegration --no-daemon
