name: Notify Pull Requests on Discord

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:

  test:
    uses: ./.github/workflows/job-unit-test.yaml@main

  notify:
    needs: test
    uses: ./.github/workflows/job-discord-notify-pull-request.yaml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_author: ${{ github.event.pull_request.user.login }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
