name: Workflow Main Merge

on:
  push:
    branches: [ main ]

jobs:

  test:
    uses: ./.github/workflows/job-unit-test.yaml

  docker:
    needs: test
    uses: ./.github/workflows/job-docker-build-push.yaml
    with:
      image_name: soatproject/fastfood-soat-app-totem
      image_tag: latest
    secrets:
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  notify:
    needs: docker
    if: ${{ always() }}
    uses: ./.github/workflows/job-discord-notify-build.yaml
    with:
      build_status: ${{ needs.docker.result }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
